/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package petcare;

/**
 *
 * @author Julian Lara
 */
public class jPnRegistro extends javax.swing.JPanel {

    /**
     * Creates new form jPnRegistro
     */
    public jPnRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        cbPropietario = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbServicio = new javax.swing.JComboBox<>();
        btnRegistro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listRegistro = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbMascota = new javax.swing.JComboBox<>();

        setMinimumSize(new java.awt.Dimension(500, 450));
        setPreferredSize(new java.awt.Dimension(500, 450));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Registro");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 43, 550, 10));

        jLabel2.setText("Cliente");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        add(cbPropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 150, -1));

        jLabel3.setText("Servicio");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        add(cbServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 120, -1));

        btnRegistro.setText("Registrar");
        add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 90, -1));

        listRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listRegistroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listRegistro);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 390, 100));

        jButton3.setText("Modificar");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 529, -1, -1));

        jButton4.setText("Finalizar");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 529, -1, -1));

        btnConsultar.setText("Consultar");
        add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        btnModificar.setText("Modificar");
        add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));

        btnFinalizar.setText("Finalizar");
        add(btnFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 90, -1));

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petcare/Img/limpiar.png"))); // NOI18N
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 60, 30));

        jLabel4.setText("Mascota");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        add(cbMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 150, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void listRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listRegistroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listRegistroMouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnConsultar;
    public javax.swing.JButton btnFinalizar;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnModificar;
    public javax.swing.JButton btnRegistro;
    public javax.swing.JComboBox<String> cbMascota;
    public javax.swing.JComboBox<String> cbPropietario;
    public javax.swing.JComboBox<String> cbServicio;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JList<String> listRegistro;
    // End of variables declaration//GEN-END:variables
}
