/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package petcare;

/**
 *
 * @author Julian Lara
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPn = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnProp = new javax.swing.JButton();
        btnMas = new javax.swing.JButton();
        btnRes = new javax.swing.JButton();
        btnCon = new javax.swing.JButton();
        btnVar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPn.setMinimumSize(new java.awt.Dimension(500, 350));
        jPn.setPreferredSize(new java.awt.Dimension(500, 400));
        jPn.setLayout(new java.awt.BorderLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 40));

        btnProp.setText("Propietarios");
        jPanel1.add(btnProp);

        btnMas.setText("Mascotas");
        jPanel1.add(btnMas);

        btnRes.setText("Registro");
        jPanel1.add(btnRes);

        btnCon.setText("Contabilidad");
        jPanel1.add(btnCon);

        btnVar.setText("Variables");
        jPanel1.add(btnVar);

        jPn.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPn, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCon;
    public javax.swing.JButton btnMas;
    public javax.swing.JButton btnProp;
    public javax.swing.JButton btnRes;
    public javax.swing.JButton btnVar;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPn;
    // End of variables declaration//GEN-END:variables

}
